name: PR Coverage Diff
branding:
  icon: trending-up
  color: green
description: Check base coverage and publish diff as PR comment.
inputs:
  github-token:
    description: A GitHub token to access coverage branch, generate diff, and write / replace PR comment.
    required: true
  generated-coverage-filepath:
    description: Path of the json-summary file(s) to analyse.
    default: coverage/coverage-summary.json
    required: false
  allowed-to-fail:
    description: When true, it will pass even if the PR decreases test coverage.
    default: "false"
    required: false
  coverage-branch:
    description: Branch on which to store base coverage.
    default: "coverage"
    required: false
runs:
  using: node16
  main: dist/index.js
